### ISSUE TITLE
See result of AOI analysis

### ISSUE THREAD

**Issue by Jking-GIS** [EsriPS/field-sustainability-helper#4]
See things like:

- a badge of health
- crop types
- acreage
- graphs??

**Comment by gavinr** [comment]
mostly done - closing

**Comment by gavinr** [comment]
![image](https://user-images.githubusercontent.com/209355/149535845-5579c7a3-0919-49b4-8c8b-0a8099d89153.png)

**Comment by gavinr** [comment]
this new grid style is mostly in place, closing.
